networks:
  inception:
    name: inception

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - 9000
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mgoedkoo/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mgoedkoo/data/wordpress
      o: bind
      type: none
